FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o billing-engine main.go

# Minimal runtime image
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/billing-engine .

EXPOSE 8082
CMD ["./billing-engine"]
